### ISSUE TITLE
Crash when inviting players

### ISSUE THREAD

**Issue by fryguy503** [Voidless22/puppetmaster#17]
When I load up puppetmaster the UI works, but as soon as I invite a player, it crashes.

![image](https://github.com/Voidless22/puppetmaster/assets/5864295/94eaabbf-999b-4fc7-b744-554edca457f2)

**Comment by Voidless22** [comment]
fixed: https://github.com/Voidless22/puppetmaster/commit/bd67965941606ae8a76f175ba91c1319dc707bcd
